version: "3.7"
services:
  airflow_postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
        - airflow_dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  airflow_initdb:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - airflow_postgres
    volumes:
      - ../airflow.cfg:/usr/local/airflow/airflow.cfg
      - ../variables:/usr/local/airflow/variables
    command:
      - bin/bash
      - -c
      - |
        airflow initdb
        if [[ -e /usr/local/airflow/variables/dev/all.json ]]; then
          airflow variables -i /usr/local/airflow/variables/dev/all.json
        fi
        # Enable this if RBAC UI is enabled
        # airflow create_user -r Admin -u airflow -e airflow@airflow.com -f Air -l Flow -p airflow

  airflow_webserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    restart: always
    depends_on:
      - airflow_initdb
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
        - ../dags:/usr/local/airflow/dags
        - ../plugins:/usr/local/airflow/plugins
        - ../airflow.cfg:/usr/local/airflow/airflow.cfg
        - ./spark-conf:/spark-conf
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  airflow_dbdata: